version: '3.8'
services:
  imdb-app:
    build: .
    ports:
      - "8765:8765"
    environment:
      - PYTHONUNBUFFERED=1
      - MDB_API_KEY=${MDB_API_KEY}
      - TMDB_API_KEY=${TMDB_API_KEY}
    restart: unless-stopped

